# Generated by Django 4.2.20 on 2025-04-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aboutme_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About me', 'verbose_name_plural': 'About me'},
        ),
    ]
