# Generated by Django 4.2.20 on 2025-04-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_address', models.CharField(max_length=255)),
                ('my_phone', models.CharField(max_length=20)),
                ('my_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'myinfo',
                'verbose_name_plural': 'myinfo',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='my_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='my_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='my_phone',
        ),
    ]
