# Generated by Django 4.2.20 on 2025-04-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myinfo_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
