# Generated by Django 4.2.20 on 2025-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_myinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinfo',
            name='my_address',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='my_email',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='my_phone',
        ),
        migrations.AddField(
            model_name='myinfo',
            name='my_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
